# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('statut_livraison', models.CharField(choices=[('PREPARATION', 'En préparation'), ('SHIPPING', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('RETURNED', 'Retournée / Échouée')], default='PREPARATION', max_length=30, verbose_name="Statut d'expédition")),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('livreur_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du livreur / coursier')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Frais de livraison')),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='ventes.order', verbose_name='Commande associée')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('frais_livraison__gte', 0)), name='chk_livraisons_fees_positive')],
            },
        ),
    ]
