# Generated by Django 5.2.10 on 2026-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0001_initial'),
        ('ventes', '0003_order_livraison_necessaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='argent_remis_a_brocard',
            field=models.BooleanField(default=False, verbose_name='Argent remis à Brocard'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='date_remise_argent',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de remise de l'argent"),
        ),
        migrations.AddField(
            model_name='delivery',
            name='livreur_prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom du livreur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='livreur_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone du livreur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='mode_paiement_recu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mode de paiement reçu'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='montant_encaisse_livreur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant encaissé par le livreur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='montant_remis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant remis à Brocard'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='livreur_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du livreur'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='statut_livraison',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SHIPPING', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('DELIVERED_COLLECTED', 'Livrée et encaissée'), ('RETURNED', 'Retournée')], default='PENDING', max_length=30, verbose_name="Statut d'expédition"),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('montant_encaisse_livreur__gte', 0)), name='chk_livraisons_collected_positive'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('montant_remis__gte', 0)), name='chk_livraisons_remitted_positive'),
        ),
    ]
