# Generated by Django 5.2.10 on 2026-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_delivery_argent_remis_a_brocard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence unique'),
        ),
    ]
