# Generated by Django 5.2.15 on 2026-06-16 11:54

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'atelier")),
                ('responsable', models.CharField(max_length=150, verbose_name='Nom du responsable')),
                ('telephone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone_number], verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Atelier de couture',
                'verbose_name_plural': 'Ateliers de couture',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence unique')),
                ('statut', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut de production')),
                ('date_debut', models.DateField(verbose_name='Date de début de fabrication')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('quantite_demandee', models.IntegerField(verbose_name='Quantité demandée')),
                ('quantite_produite', models.IntegerField(default=0, verbose_name='Quantité conforme produite')),
                ('pieces_defectueuses', models.IntegerField(default=0, verbose_name='Pièces défectueuses / rebutées')),
                ('cout_facon_unitaire', models.DecimalField(decimal_places=2, help_text="Montant facturé par l'atelier pour assembler une seule pièce.", max_digits=12, verbose_name='Coût de façon unitaire')),
                ('montant_facon_total', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : quantite_produite * cout_facon_unitaire.', max_digits=12, verbose_name='Montant façon total')),
                ('montant_facon_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant façon réglé')),
                ('statut_paiement_facon', models.CharField(choices=[('UNPAID', 'Non payé'), ('PARTIALLY_PAID', 'Partiellement payé'), ('PAID', 'Payé'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=25, verbose_name='Statut du paiement de la façon')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_orders', to='production.workshop', verbose_name='Atelier de couture')),
            ],
            options={
                'verbose_name': 'Ordre de production',
                'verbose_name_plural': 'Ordres de production',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé')),
                ('mode_paiement', models.CharField(help_text='Ex: Espèces, Mobile Money, Virement, Chèque', max_length=50, verbose_name='Mode de règlement')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, verbose_name='Référence de la transaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='production.productionorder', verbose_name='Ordre de production')),
            ],
            options={
                'verbose_name': "Paiement d'atelier",
                'verbose_name_plural': "Paiements d'ateliers",
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee_metres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité consommée (mètres / unités)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consumptions', to='achats.rawmaterial', verbose_name='Matière première consommée')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.productionorder', verbose_name='Ordre de production')),
            ],
            options={
                'verbose_name': 'Consommation de matière',
                'verbose_name_plural': 'Consommations de matières',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite_utilisee_metres__gt', 0)), name='chk_prod_consumption_qty_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['reference'], name='idx_prod_reference'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['statut'], name='idx_prod_status'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_demandee__gt', 0)), name='chk_prod_quantity_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_produite__gte', 0)), name='chk_prod_quantity_produced_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('pieces_defectueuses__gte', 0)), name='chk_prod_pieces_defective_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('cout_facon_unitaire__gte', 0)), name='chk_prod_labor_unit_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('montant_facon_total__gte', 0)), name='chk_prod_labor_total_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('montant_facon_paye__gte', 0)), name='chk_prod_labor_paid_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('montant_facon_paye__lte', models.F('montant_facon_total'))), name='chk_prod_labor_paid_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='workshoppayment',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='chk_prod_payment_amount_positive'),
        ),
    ]
