# Generated by Django 5.2.10 on 2026-06-16 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='production_orders', to='catalogue.clothingmodel', verbose_name="Modèle d'habit"),
        ),
    ]
