# Generated by Django 5.2.15 on 2026-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('production', '0002_productionorder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='cout_revient_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Coût de revient unitaire'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('cout_revient_unitaire__gte', 0)), name='chk_prod_revient_cost_positive'),
        ),
    ]
