# Generated by Django 5.2.10 on 2026-06-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder_cout_revient_unitaire_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionorder',
            name='chk_prod_labor_paid_lte_total',
        ),
    ]
