# Generated by Django 5.2.15 on 2026-06-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_pricecategory_remove_clothingmodel_stock_initial_and_more'),
        ('production', '0004_remove_productionorder_chk_prod_labor_paid_lte_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='production_orders', to='catalogue.pricecategory', verbose_name='Catégorie de prix'),
        ),
    ]
