# Generated by Django 5.2.10 on 2026-06-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_clothingmodel_category'),
        ('production', '0005_productionorder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='production_orders', to='catalogue.pricecategory', verbose_name='Catégorie de prix'),
            preserve_default=False,
        ),
    ]
