# Generated by Django 5.2.10 on 2026-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionorder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppayment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence unique'),
        ),
    ]
