# Generated by Django 5.2.10 on 2026-06-20 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_workshoppayment_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='statut',
            field=models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('PARTIAL', 'Réception partielle'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut de production'),
        ),
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantite_recue', models.IntegerField(verbose_name='Quantité reçue')),
                ('date_reception', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.productionorder', verbose_name='Ordre de production')),
            ],
            options={
                'verbose_name': 'Réception de fabrication',
                'verbose_name_plural': 'Réceptions de fabrications',
                'ordering': ['-date_reception'],
            },
        ),
    ]
