# Generated by Django 5.2.10 on 2026-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_productionorder_statut_productionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='cout_confection_historique',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Coût de confection (historique)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='cout_matieres_premieres_historique',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Coût des matières premières (historique)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='depenses_associees_historique',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Dépenses associées (historique)'),
        ),
    ]
