# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('categorie', models.CharField(choices=[('TRANSPORT', 'Transport'), ('FOOD', 'Nourriture'), ('DRINKS', 'Eau / Boisson'), ('FUEL', 'Carburant'), ('COMMUNICATION', 'Communication'), ('COMPENSATION', 'Rémunérations'), ('OTHER', 'Autre')], max_length=50, verbose_name='Catégorie de charge')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dépensé')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée / Motif')),
                ('ordre_production', models.ForeignKey(blank=True, help_text="Laissez vide si c'est une charge d'exploitation générale.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='production.productionorder', verbose_name='Ordre de production imputé')),
                ('session_caisse', models.ForeignKey(blank=True, help_text='Renseigné uniquement si la dépense a été prélevée directement du tiroir-caisse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='caisse.cashsession', verbose_name='Session de caisse associée')),
            ],
            options={
                'verbose_name': 'Dépense annexe',
                'verbose_name_plural': 'Dépenses annexes',
                'ordering': ['-date_depense', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='chk_depenses_amount_positive')],
            },
        ),
    ]
