# Generated by Django 5.2.10 on 2026-06-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_rawmaterial_categorie_rawmaterial_unite_mesure'),
        ('depenses', '0002_expense_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fabric_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='achats.fabricpurchase', verbose_name='Achat de tissu associé'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('FOOD', 'Nourriture'), ('DRINKS', 'Eau / Boisson'), ('FUEL', 'Carburant'), ('COMMUNICATION', 'Communication'), ('COMPENSATION', 'Rémunérations'), ('RAW_MAT', 'Achat Matières Premières'), ('OTHER', 'Autre')], max_length=50, verbose_name='Catégorie de charge'),
        ),
    ]
