# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remunerations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('opening_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure d'ouverture")),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fermeture')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant initial (fond de caisse)')),
                ('cash_sales_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventes encaissées (espèces)')),
                ('cash_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Dépenses de caisse')),
                ('theoretical_amount', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : initial_amount + cash_sales_collected - cash_expenses.', max_digits=12, verbose_name='Montant théorique attendu')),
                ('real_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant réel compté (à la fermeture)')),
                ('cash_discrepancy', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement : real_amount - theoretical_amount.', max_digits=12, null=True, verbose_name='Écart de caisse')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Fermée')], default='OPEN', max_length=20, verbose_name='Statut de la session')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_sessions', to='remunerations.companymember', verbose_name='Responsable de caisse')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opening_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('initial_amount__gte', 0)), name='chk_caisse_initial_amount_positive'), models.CheckConstraint(condition=models.Q(('cash_sales_collected__gte', 0)), name='chk_caisse_sales_collected_positive'), models.CheckConstraint(condition=models.Q(('cash_expenses__gte', 0)), name='chk_caisse_expenses_positive'), models.CheckConstraint(condition=models.Q(('theoretical_amount__gte', 0)), name='chk_caisse_theoretical_amount_positive')],
            },
        ),
    ]
