# Generated by Django 5.2.10 on 2026-06-17 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        ('depenses', '0001_initial'),
        ('production', '0003_productionorder_cout_revient_unitaire_and_more'),
        ('remunerations', '0001_initial'),
        ('ventes', '0003_order_livraison_necessaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('mode_paiement', models.CharField(help_text='Ex: Espèces, Orange Money, Wave, Virement bancaire', max_length=50, verbose_name='Mode de paiement')),
                ('description', models.TextField(blank=True, verbose_name='Description / Motif')),
                ('compensation_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='remunerations.compensationpayment')),
                ('customer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='ventes.customerpayment')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='depenses.expense')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='ventes.reservation')),
                ('salary_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='remunerations.salaryadvance')),
                ('workshop_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisse_movements', to='production.workshoppayment')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-date_mouvement', '-id'],
            },
        ),
    ]
