# Generated by Django 5.2.10 on 2026-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, verbose_name='Préfixe du document')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('last_sequence', models.IntegerField(default=0, verbose_name='Dernière séquence générée')),
            ],
            options={
                'verbose_name': 'Séquence de référence',
                'verbose_name_plural': 'Séquences de références',
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
