# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_retour', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du retour')),
                ('statut_retour', models.CharField(choices=[('RECEIVED', 'Reçu'), ('INSPECTED', 'Inspecté'), ('CLOSED', 'Clôturé')], default='RECEIVED', max_length=30, verbose_name='Statut du retour')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant remboursé (espèces)')),
                ('accredite_avoir', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Crédit d'avoir accordé (code d'achat)")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns', to='ventes.order', verbose_name="Commande d'origine")),
            ],
            options={
                'verbose_name': 'Retour client',
                'verbose_name_plural': 'Retours clients',
                'ordering': ['-date_retour'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité retournée')),
                ('motif', models.CharField(choices=[('WRONG_SIZE', 'Taille incorrecte'), ('WRONG_COLOR', 'Couleur incorrecte'), ('DEFECTIVE', 'Défaut produit'), ('REFUSED_DELIVERY', 'Refus de livraison')], max_length=50, verbose_name='Motif de retour')),
                ('reintegre_stock', models.BooleanField(default=True, help_text="Si coché, l'habit est replacé en stock disponible. Sinon, il est dirigé vers la quarantaine (défaut).", verbose_name='Réintégrer au stock commercialisable')),
                ('notes', models.TextField(blank=True, verbose_name="Notes / Détails sur l'état")),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='retours.customerreturn', verbose_name='Retour associé')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returned_lines', to='catalogue.productvariant', verbose_name="Variante d'habit retournée")),
            ],
            options={
                'verbose_name': 'Ligne de retour',
                'verbose_name_plural': 'Lignes de retours',
            },
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.CheckConstraint(condition=models.Q(('montant_rembourse__gte', 0)), name='chk_retours_refund_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.CheckConstraint(condition=models.Q(('accredite_avoir__gte', 0)), name='chk_retours_credit_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='chk_retours_line_qty_positive'),
        ),
    ]
