# Generated by Django 5.2.15 on 2026-06-16 11:54

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet du client')),
                ('telephone', models.CharField(max_length=20, unique=True, validators=[apps.core.validators.validate_phone_number], verbose_name='Numéro de téléphone')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville de résidence')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence unique')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de la commande')),
                ('canal_vente', models.CharField(choices=[('TIKTOK_LIVE', 'TikTok Live'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('BOUTIQUE', 'Boutique Physique'), ('TELEPHONE', 'Téléphone')], max_length=30, verbose_name='Canal de vente')),
                ('statut_commande', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('SHIPPING', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée'), ('RETURNED', 'Retournée')], default='DRAFT', max_length=30, verbose_name='Statut de la commande')),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Somme des lignes de commande + frais éventuels - remises.', max_digits=12, verbose_name='Montant total de la commande')),
                ('acompte_verse', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Acompte versé par le client')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : montant_total - acompte_verse.', max_digits=12, verbose_name='Reste à payer')),
                ('statut_paiement', models.CharField(choices=[('UNPAID', 'Non payé'), ('PARTIALLY_PAID', 'Partiellement payé'), ('PAID', 'Payé'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=30, verbose_name='Statut du paiement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='ventes.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé')),
                ('type_paiement', models.CharField(choices=[('DEPOSIT', 'Acompte de garantie'), ('BALANCE', 'Solde de commande'), ('FULL', 'Paiement complet initial')], max_length=30, verbose_name='Type de versement')),
                ('mode_paiement', models.CharField(help_text='Ex: Espèces, Mobile Money, Virement, Contre-remboursement', max_length=50, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('session_caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='caisse.cashsession', verbose_name='Session de caisse associée')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='ventes.order', verbose_name='Commande associée')),
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': 'Paiements clients',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité commandée')),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire appliqué')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventes.order', verbose_name='Commande associée')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_lines', to='catalogue.productvariant', verbose_name="Variante d'habit vendue")),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commandes',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference'], name='idx_orders_ref'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['canal_vente', 'date_commande'], name='idx_orders_channel_date'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='chk_ventes_order_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('acompte_verse__gte', 0)), name='chk_ventes_order_deposit_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('reste_a_payer__gte', 0)), name='chk_ventes_order_due_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('acompte_verse__lte', models.F('montant_total'))), name='chk_ventes_deposit_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='chk_ventes_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='chk_ventes_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire_applique__gte', 0)), name='chk_ventes_line_price_positive'),
        ),
    ]
