# Generated by Django 5.2.10 on 2026-06-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_clothingmodel_is_archived_clothingmodel_is_available'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence de réservation')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité réservée')),
                ('date_limite', models.DateField(verbose_name='Date limite de retrait')),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant versé (acompte)')),
                ('montant_restant', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : (quantite * prix_vente_conseille) - montant_verse.', max_digits=12, verbose_name='Montant restant à payer')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Récupérée / Validée'), ('CANCELLED', 'Annulée / Dépassée')], default='PENDING', max_length=30, verbose_name='Statut de la réservation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='ventes.customer', verbose_name='Client')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='catalogue.clothingmodel', verbose_name='Modèle réservé')),
            ],
            options={
                'verbose_name': 'Réservation client',
                'verbose_name_plural': 'Réservations clients',
                'ordering': ['-date_limite', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='chk_ventes_res_qty_positive'), models.CheckConstraint(condition=models.Q(('montant_verse__gte', 0)), name='chk_ventes_res_paid_positive'), models.CheckConstraint(condition=models.Q(('montant_restant__gte', 0)), name='chk_ventes_res_remaining_positive')],
            },
        ),
    ]
