# Generated by Django 5.2.10 on 2026-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='livraison_necessaire',
            field=models.BooleanField(default=False, verbose_name='Livraison nécessaire'),
        ),
    ]
