# Generated by Django 5.2.10 on 2026-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_order_livraison_necessaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, verbose_name='Quartier de résidence'),
        ),
    ]
