# Generated by Django 5.2.15 on 2026-06-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_customerpayment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ventes.reservation', verbose_name='Réservation associée'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order', to='ventes.reservation', verbose_name="Réservation d'origine"),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='ventes.order', verbose_name='Commande associée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('COMPLETED', 'Récupérée'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=30, verbose_name='Statut de la réservation'),
        ),
    ]
