# Generated by Django 5.2.15 on 2026-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_customerpayment_reservation_order_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAIEMENT_PARTIEL', 'Paiement partiel'), ('PAYEE', 'Payée'), ('RECUPEREE', 'Récupérée'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=30, verbose_name='Statut de la réservation'),
        ),
    ]
