# Generated by Django 5.2.10 on 2026-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_migrate_reservation_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence unique'),
        ),
    ]
