# Generated by Django 5.2.15 on 2026-06-16 11:54

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du fournisseur')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable / Contact')),
                ('telephone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone_number], verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FabricPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Montant total d'achat")),
                ('statut_paiement', models.CharField(choices=[('UNPAID', 'Non payé'), ('PARTIALLY_PAID', 'Partiellement payé'), ('PAID', 'Payé'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=25, verbose_name='Statut du paiement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchases', to='achats.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Achat de tissu',
                'verbose_name_plural': 'Achats de tissus',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('type_matiere', models.CharField(help_text='Ex: Brocard Soie Or, Doublure Satin, Bouton Métal', max_length=100, verbose_name='Type de matière première')),
                ('couleur', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('quantite_achetee_metres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité achetée (mètres / unités)')),
                ('quantite_restante_metres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité restante en stock')),
                ('prix_achat_metre', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat unitaire")),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('fabric_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='achats.fabricpurchase', verbose_name='Achat associé')),
            ],
            options={
                'verbose_name': 'Matière première',
                'verbose_name_plural': 'Matières premières',
                'ordering': ['-date_reception'],
                'indexes': [models.Index(fields=['type_matiere', 'couleur'], name='idx_raw_material_spec')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite_achetee_metres__gte', 0)), name='chk_achats_quantity_purchased_positive'), models.CheckConstraint(condition=models.Q(('quantite_restante_metres__gte', 0)), name='chk_achats_quantity_remaining_positive'), models.CheckConstraint(condition=models.Q(('prix_achat_metre__gte', 0)), name='chk_achats_price_positive'), models.CheckConstraint(condition=models.Q(('quantite_restante_metres__lte', models.F('quantite_achetee_metres'))), name='chk_achats_remaining_lte_purchased')],
            },
        ),
        migrations.AddConstraint(
            model_name='fabricpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='chk_achats_total_amount_positive'),
        ),
    ]
