# Generated by Django 5.2.15 on 2026-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
