# Generated by Django 5.2.15 on 2026-06-17 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_rawmaterial_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancienne quantité')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nouvelle quantité')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Différence')),
                ('operation_type', models.CharField(choices=[('PURCHASE', 'Achat'), ('CONSUMPTION', 'Consommation atelier'), ('CORRECTION', 'Correction'), ('RETURN', 'Retour'), ('ADJUSTMENT', 'Ajustement manuel')], max_length=30, verbose_name="Type d'opération")),
                ('description', models.TextField(blank=True, verbose_name='Description / Notes')),
            ],
            options={
                'verbose_name': 'Mouvement de matière première',
                'verbose_name_plural': 'Mouvements de matières premières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name="Seuil d'alerte de stock"),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('seuil_alerte__gte', 0)), name='chk_achats_seuil_alerte_positive'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='achats.rawmaterial', verbose_name='Matière première'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_movements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
