# Generated by Django 5.2.10 on 2026-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_rawmaterialmovement_rawmaterial_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='categorie',
            field=models.CharField(choices=[('TISSU', 'Tissu'), ('FIL', 'Fil'), ('PERLE', 'Perle'), ('FERMETURE', 'Fermeture'), ('BOUTON', 'Bouton'), ('GARNITURE', 'Garniture'), ('EMBALLAGE', 'Emballage'), ('AUTRE', 'Autre')], default='TISSU', max_length=30, verbose_name='Catégorie de matière première'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unite_mesure',
            field=models.CharField(choices=[('mètres', 'Mètres'), ('bobines', 'Bobines'), ('sachets', 'Sachets'), ('unités', 'Unités'), ('rouleaux', 'Rouleaux'), ('paquets', 'Paquets'), ('boîtes', 'Boîtes'), ('autre', 'Autre')], default='mètres', max_length=30, verbose_name='Unité de mesure'),
        ),
    ]
