# Generated by Django 5.2.10 on 2026-06-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_rawmaterial_categorie_rawmaterial_unite_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricpurchase',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence unique'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials_direct', to='achats.supplier', verbose_name='Fournisseur'),
        ),
    ]
