# Generated by Django 5.2.10 on 2026-06-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_fabricpurchase_reference_rawmaterial_date_achat_and_more'),
        ('production', '0008_alter_productionorder_statut_productionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='fabric_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_movements', to='achats.fabricpurchase', verbose_name="Achat d'origine"),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_movements', to='production.productionorder', verbose_name="Ordre de production d'origine"),
        ),
    ]
