# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo_principale', models.ImageField(upload_to='catalogue/photos/', verbose_name='Photo principale')),
                ('prix_vente_conseille', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente conseillé')),
            ],
            options={
                'verbose_name': "Modèle d'habit",
                'verbose_name_plural': "Modèles d'habits",
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('prix_vente_conseille__gte', 0)), name='chk_catalogue_suggested_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='ModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/gallery/', verbose_name='Photo')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='catalogue.clothingmodel', verbose_name="Modèle d'habit")),
            ],
            options={
                'verbose_name': 'Photo de modèle',
                'verbose_name_plural': 'Photos de modèles',
                'ordering': ['ordre_affichage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Code SKU')),
                ('taille', models.CharField(max_length=20, verbose_name='Taille')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur')),
                ('prix_vente_specifique', models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide pour utiliser le prix de vente conseillé du modèle.', max_digits=12, null=True, verbose_name='Prix de vente spécifique')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='catalogue.clothingmodel', verbose_name="Modèle d'habit")),
            ],
            options={
                'verbose_name': 'Variante produit',
                'verbose_name_plural': 'Variantes produits',
                'ordering': ['model', 'taille', 'couleur'],
                'indexes': [models.Index(fields=['sku'], name='idx_variant_sku'), models.Index(fields=['taille', 'couleur'], name='idx_variant_specs')],
                'constraints': [models.UniqueConstraint(fields=('model', 'taille', 'couleur'), name='uq_variant_model_size_color'), models.CheckConstraint(condition=models.Q(('prix_vente_specifique__gte', 0), ('prix_vente_specifique__isnull', True), _connector='OR'), name='chk_catalogue_variant_price_positive')],
            },
        ),
    ]
