# Generated by Django 5.2.10 on 2026-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_clothingmodel_is_archived_clothingmodel_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingmodel',
            name='stock_initial',
            field=models.IntegerField(default=0, help_text='Stock de départ créé automatiquement à la création.', verbose_name='Stock initial'),
        ),
    ]
