# Generated by Django 5.2.15 on 2026-06-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_clothingmodel_stock_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, unique=True, verbose_name='Prix de la catégorie')),
                ('stock_global', models.IntegerField(default=0, verbose_name='Stock global de robes')),
            ],
            options={
                'verbose_name': 'Catégorie de prix',
                'verbose_name_plural': 'Catégories de prix',
                'ordering': ['prix'],
            },
        ),
        migrations.RemoveField(
            model_name='clothingmodel',
            name='stock_initial',
        ),
        migrations.AddField(
            model_name='clothingmodel',
            name='quantite_affectee',
            field=models.IntegerField(default=0, help_text='Nombre de robes de la catégorie globale affectées à ce design.', verbose_name='Quantité affectée'),
        ),
        migrations.AddField(
            model_name='clothingmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='designs', to='catalogue.pricecategory', verbose_name='Catégorie de prix'),
        ),
    ]
