# Generated by Django 5.2.10 on 2026-06-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_pricecategory_remove_clothingmodel_stock_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='designs', to='catalogue.pricecategory', verbose_name='Catégorie de prix'),
            preserve_default=False,
        ),
    ]
