# Generated by Django 5.2.10 on 2026-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_clothingmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingmodel',
            name='cout_confection',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Coût de confection'),
        ),
        migrations.AddField(
            model_name='clothingmodel',
            name='cout_matieres_premieres',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Coût des matières premières'),
        ),
        migrations.AddField(
            model_name='clothingmodel',
            name='depenses_associees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Dépenses associées'),
        ),
    ]
