# Generated by Django 5.2.15 on 2026-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantite_reel', models.IntegerField(default=0, verbose_name='Quantité réelle physique')),
                ('quantite_reservee', models.IntegerField(default=0, help_text='Quantité vendue mais non encore livrée ou récupérée.', verbose_name='Quantité réservée')),
                ('emplacement', models.CharField(default='Magasin', help_text='Ex: Magasin, Dépôt A, Quarantaine Défectueux', max_length=100, verbose_name='Emplacement du stock')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='catalogue.productvariant', verbose_name="Variante d'habit")),
            ],
            options={
                'verbose_name': 'Stock produit fini',
                'verbose_name_plural': 'Stocks produits finis',
                'ordering': ['emplacement', 'variant'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='Valeur positive pour les entrées, négative pour les sorties.', verbose_name='Quantité déplacée')),
                ('type_mouvement', models.CharField(choices=[('ENTRY', 'Entrée (Production / Restock)'), ('EXIT', 'Sortie (Vente)'), ('RETURN', 'Retour client'), ('ADJUSTMENT', 'Ajustement inventaire'), ('REJECT', 'Mise au rebut')], max_length=30, verbose_name='Type de mouvement')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description / Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stocks.finishedgoodstock', verbose_name='Stock affecté')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='finishedgoodstock',
            index=models.Index(fields=['emplacement', 'variant'], name='idx_stocks_loc_var'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstock',
            constraint=models.UniqueConstraint(fields=('variant', 'emplacement'), name='uq_stocks_variant_location'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_reel__gte', 0)), name='chk_stocks_quantite_reel_positive'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_reservee__gte', 0)), name='chk_stocks_quantite_reservee_positive'),
        ),
    ]
