# Generated by Django 5.2.15 on 2026-06-16 11:54

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle / Poste occupé')),
                ('telephone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone_number], verbose_name='Téléphone')),
                ('remuneration_mensuelle_standard', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rémunération mensuelle de base')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Membre de l'entreprise",
                'verbose_name_plural': "Membres de l'entreprise",
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('mois', models.IntegerField(help_text='Valeur numérique de 1 (Janvier) à 12 (Décembre).', verbose_name='Mois de règlement')),
                ('annee', models.IntegerField(verbose_name='Année de règlement')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant brut dû')),
                ('avances_deduites', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Avances de salaires déduites')),
                ('net_amount_payable', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : montant_du - avances_deduites.', max_digits=12, verbose_name='Montant net à payer')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant réglé effectif')),
                ('amount_remaining', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement : net_amount_payable - paid_amount.', max_digits=12, verbose_name='Reste à régler')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Non payé'), ('PARTIALLY_PAID', 'Partiellement payé'), ('PAID', 'Payé'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=25, verbose_name='Statut du paiement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='monthly_compensations', to='remunerations.companymember', verbose_name='Collaborateur')),
            ],
            options={
                'verbose_name': 'Rémunération mensuelle',
                'verbose_name_plural': 'Rémunérations mensuelles',
                'ordering': ['-annee', '-mois', 'member'],
            },
        ),
        migrations.CreateModel(
            name='CompensationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé')),
                ('payment_mode', models.CharField(help_text='Ex: Espèces, Virement, Mobile Money', max_length=50, verbose_name='Mode de versement')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de la transaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Détails')),
                ('monthly_compensation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='remunerations.monthlycompensation', verbose_name='Fiche de paie mensuelle')),
            ],
            options={
                'verbose_name': 'Paiement de rémunération',
                'verbose_name_plural': 'Paiements de rémunérations',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('grant_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'octroi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant accordé')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('DEDUCTED', 'Déduite'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=30, verbose_name="Statut de l'avance")),
                ('notes', models.TextField(blank=True, verbose_name='Notes explicatives')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salary_advances', to='remunerations.companymember', verbose_name='Collaborateur')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaires',
                'ordering': ['-grant_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.UniqueConstraint(fields=('member', 'mois', 'annee'), name='uq_remun_member_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='chk_remun_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('montant_du__gte', 0)), name='chk_remun_due_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('avances_deduites__gte', 0)), name='chk_remun_advances_deducted_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount_payable__gte', 0)), name='chk_remun_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='chk_remun_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_remaining__gte', 0)), name='chk_remun_remaining_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('avances_deduites__lte', models.F('montant_du'))), name='chk_remun_advances_deducted_lte_due'),
        ),
        migrations.AddConstraint(
            model_name='monthlycompensation',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('net_amount_payable'))), name='chk_remun_paid_lte_net'),
        ),
        migrations.AddConstraint(
            model_name='compensationpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_remun_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_remun_advance_amount_positive'),
        ),
    ]
