# Generated by Django 5.2.10 on 2026-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remunerations', '0002_compensationpayment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryadvance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('DEDUCTED', 'Déduite')], default='PENDING', max_length=30, verbose_name="Statut de l'avance"),
        ),
    ]
