# Generated by Django 5.2.10 on 2026-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remunerations', '0003_alter_salaryadvance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycompensation',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence unique'),
        ),
    ]
